class pizza{
constructor(s,mt,vt){
this.size=s;
this.meattoppings=mt;
this.veggietoppings=vt;

sizecost(){
    if (this.size==s) {
        return 7.99
    }
    if (this.size==m) {
        return 9.99
    }
    if(this.size==l){
        return 12.99
    }
    if(this.size=xl){
        return 15.99
    }
    else "Pick the pizza size bud"{
    }
toppingcost()
    if {top=this.meattoppings){
        return top.length*.99
    }
        else if (top=this.veggietoppings) {
            return top.length*.50
        }
price(){
return this.sizecost() this.toppingcost()

}
static.promotionalDeal(pizza,percent){
return this.price()*
}


















    }



price()


  //type class functions below
promotionalDeal()

}
