//Pomykalas's pizza parlor


 How about a slice?
                      _________
                      |  ~ ~--.
                       |%= @%%/
                       |o% %%/
                 __    |% %o/
           _,-- ~~   | |(_/ . _
        ,/'   m% %%% | |o/  /  `\.
       /' m% %o( _)% | |/  /o%%m `\
     /' %%@= %o% %%o |   / (_)o %%% `\
    /  %o%%% %%= @%% |  /% %o%% @=%%  \
   |  (_)%(_ )%% o%% | /%% %=@( _)%%%  |
   | %%o%%%% o%% %(_ |/%o% %o%% %%o%%% |
   | %%o%(_) %%% %%o% (_)% %%o% %o%o%% |
   |  (_)%%= @%( _)%o %o%% (_)% o(_)%  |
    \ ~%%o%% %%% o%o% =@%% o%%@ %%o%~ /
     \. ~o%% (_) %%%o %(_) %%(_ )o~ ,/
       \_ ~o% =@ %(_) %o%% (_)% ~ _/
         `\_~ ~o %%%o %%% %%~~ _  / '
            `--..____,,--'



class pizza{
constructor(s,mt,vt){
this.size=s;
this.meattoppings=mt;
this.veggietoppings=vt;

sizecost(){
    if (this.size=="s") {
        return 7.99
    }
    if (this.size=="m") {
        return 9.99
    }
    if(this.size=="l"){
        return 12.99
    }
    if(this.size=="xl"){
        return 15.99
    }
    else {
      console.log("Pick the pizza size bud");
    }
toppingcost()
    if {top=="meat"){
        return top.length*.99
    }
        else if (top=="veggie") {
            return top.length*.50
        }
price(){
return this.sizecost() this.toppingcost("meat")this.toppingcost("veggie")

}
static.promotionalDeal(pizza,percent){
return this.price()==this.price()*5%
return totalcost
}


















    }



price()


  //type class functions below
promotionalDeal()

}
